//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18046
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Chronocourses.Client.ShopService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class Shop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.Address AddressField;
        
        private int AddressIDField;
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Entity> EntityField;
        
        private short HeightField;
        
        private int IDField;
        
        private string NameField;
        
        private short WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Entity> Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private string CityField;
        
        private string CountryField;
        
        private int IDField;
        
        private short NumberField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> ShopField;
        
        private string StreetField;
        
        private int ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> Shop {
            get {
                return this.ShopField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopField, value) != true)) {
                    this.ShopField = value;
                    this.RaisePropertyChanged("Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectChangeTracker", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class ObjectChangeTracker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.ExtendedPropertiesDictionary ExtendedPropertiesField;
        
        private Chronocourses.Client.ShopService.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionPropertiesField;
        
        private Chronocourses.Client.ShopService.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionPropertiesField;
        
        private Chronocourses.Client.ShopService.OriginalValuesDictionary OriginalValuesField;
        
        private Chronocourses.Client.ShopService.ObjectState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ExtendedPropertiesDictionary ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionProperties {
            get {
                return this.ObjectsAddedToCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsAddedToCollectionPropertiesField, value) != true)) {
                    this.ObjectsAddedToCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsAddedToCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionProperties {
            get {
                return this.ObjectsRemovedFromCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsRemovedFromCollectionPropertiesField, value) != true)) {
                    this.ObjectsRemovedFromCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsRemovedFromCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.OriginalValuesDictionary OriginalValues {
            get {
                return this.OriginalValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalValuesField, value) != true)) {
                    this.OriginalValuesField = value;
                    this.RaisePropertyChanged("OriginalValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class Entity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private bool ContainerField;
        
        private int IDField;
        
        private string LabelField;
        
        private int PositionXField;
        
        private int PositionYField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> ProductField;
        
        private Chronocourses.Client.ShopService.Shop ShopField;
        
        private int ShopIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Container {
            get {
                return this.ContainerField;
            }
            set {
                if ((this.ContainerField.Equals(value) != true)) {
                    this.ContainerField = value;
                    this.RaisePropertyChanged("Container");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionX {
            get {
                return this.PositionXField;
            }
            set {
                if ((this.PositionXField.Equals(value) != true)) {
                    this.PositionXField = value;
                    this.RaisePropertyChanged("PositionX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionY {
            get {
                return this.PositionYField;
            }
            set {
                if ((this.PositionYField.Equals(value) != true)) {
                    this.PositionYField = value;
                    this.RaisePropertyChanged("PositionY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.Shop Shop {
            get {
                return this.ShopField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopField, value) != true)) {
                    this.ShopField = value;
                    this.RaisePropertyChanged("Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopID {
            get {
                return this.ShopIDField;
            }
            set {
                if ((this.ShopIDField.Equals(value) != true)) {
                    this.ShopIDField = value;
                    this.RaisePropertyChanged("ShopID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, Chronocourses.Client.ShopService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, Chronocourses.Client.ShopService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="ObjectValue")]
    public class ObjectList : System.Collections.ObjectModel.ObservableCollection<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool AvailableField;
        
        private Chronocourses.Client.ShopService.Brand BrandField;
        
        private int BrandIDField;
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private string DescriptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Entity> EntityField;
        
        private int IDField;
        
        private string NameField;
        
        private double PriceField;
        
        private Chronocourses.Client.ShopService.TypeProduct TypeProductField;
        
        private int TypeProductIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.Brand Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Entity> Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.TypeProduct TypeProduct {
            get {
                return this.TypeProductField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeProductField, value) != true)) {
                    this.TypeProductField = value;
                    this.RaisePropertyChanged("TypeProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeProductID {
            get {
                return this.TypeProductIDField;
            }
            set {
                if ((this.TypeProductIDField.Equals(value) != true)) {
                    this.TypeProductIDField = value;
                    this.RaisePropertyChanged("TypeProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class Brand : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private int IDField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> ProductField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeProduct", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", IsReference=true)]
    public partial class TypeProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTrackerField;
        
        private int IDField;
        
        private string LabelField;
        
        private System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> ProductField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chronocourses.Client.ShopService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShopService.IShopService")]
    public interface IShopService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/GetShops", ReplyAction="http://tempuri.org/IShopService/GetShopsResponse")]
        System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> EndGetShops(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/GetShop", ReplyAction="http://tempuri.org/IShopService/GetShopResponse")]
        System.IAsyncResult BeginGetShop(int id, System.AsyncCallback callback, object asyncState);
        
        Chronocourses.Client.ShopService.Shop EndGetShop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/SaveShop", ReplyAction="http://tempuri.org/IShopService/SaveShopResponse")]
        System.IAsyncResult BeginSaveShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        int EndSaveShop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/moveEntityFromShop", ReplyAction="http://tempuri.org/IShopService/moveEntityFromShopResponse")]
        System.IAsyncResult BeginmoveEntityFromShop(Chronocourses.Client.ShopService.Entity ent, System.Collections.ObjectModel.ObservableCollection<int> newPos, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        int EndmoveEntityFromShop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/AddShop", ReplyAction="http://tempuri.org/IShopService/AddShopResponse")]
        System.IAsyncResult BeginAddShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        int EndAddShop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/DeleteShop", ReplyAction="http://tempuri.org/IShopService/DeleteShopResponse")]
        System.IAsyncResult BeginDeleteShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        int EndDeleteShop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/GetEntityByPosition", ReplyAction="http://tempuri.org/IShopService/GetEntityByPositionResponse")]
        System.IAsyncResult BeginGetEntityByPosition(int x, int y, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        Chronocourses.Client.ShopService.Entity EndGetEntityByPosition(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/GetProductsByProductType", ReplyAction="http://tempuri.org/IShopService/GetProductsByProductTypeResponse")]
        System.IAsyncResult BeginGetProductsByProductType(int productTypeId, int shopId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> EndGetProductsByProductType(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IShopService/GetStartPosition", ReplyAction="http://tempuri.org/IShopService/GetStartPositionResponse")]
        System.IAsyncResult BeginGetStartPosition(int ShopID, System.AsyncCallback callback, object asyncState);
        
        Chronocourses.Client.ShopService.Entity EndGetStartPosition(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServiceChannel : Chronocourses.Client.ShopService.IShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Chronocourses.Client.ShopService.Shop Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Chronocourses.Client.ShopService.Shop)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class moveEntityFromShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public moveEntityFromShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntityByPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEntityByPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Chronocourses.Client.ShopService.Entity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Chronocourses.Client.ShopService.Entity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductsByProductTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductsByProductTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStartPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStartPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Chronocourses.Client.ShopService.Entity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Chronocourses.Client.ShopService.Entity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServiceClient : System.ServiceModel.ClientBase<Chronocourses.Client.ShopService.IShopService>, Chronocourses.Client.ShopService.IShopService {
        
        private BeginOperationDelegate onBeginGetShopsDelegate;
        
        private EndOperationDelegate onEndGetShopsDelegate;
        
        private System.Threading.SendOrPostCallback onGetShopsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetShopDelegate;
        
        private EndOperationDelegate onEndGetShopDelegate;
        
        private System.Threading.SendOrPostCallback onGetShopCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveShopDelegate;
        
        private EndOperationDelegate onEndSaveShopDelegate;
        
        private System.Threading.SendOrPostCallback onSaveShopCompletedDelegate;
        
        private BeginOperationDelegate onBeginmoveEntityFromShopDelegate;
        
        private EndOperationDelegate onEndmoveEntityFromShopDelegate;
        
        private System.Threading.SendOrPostCallback onmoveEntityFromShopCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddShopDelegate;
        
        private EndOperationDelegate onEndAddShopDelegate;
        
        private System.Threading.SendOrPostCallback onAddShopCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteShopDelegate;
        
        private EndOperationDelegate onEndDeleteShopDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteShopCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEntityByPositionDelegate;
        
        private EndOperationDelegate onEndGetEntityByPositionDelegate;
        
        private System.Threading.SendOrPostCallback onGetEntityByPositionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductsByProductTypeDelegate;
        
        private EndOperationDelegate onEndGetProductsByProductTypeDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductsByProductTypeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStartPositionDelegate;
        
        private EndOperationDelegate onEndGetStartPositionDelegate;
        
        private System.Threading.SendOrPostCallback onGetStartPositionCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ShopServiceClient() {
        }
        
        public ShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetShopsCompletedEventArgs> GetShopsCompleted;
        
        public event System.EventHandler<GetShopCompletedEventArgs> GetShopCompleted;
        
        public event System.EventHandler<SaveShopCompletedEventArgs> SaveShopCompleted;
        
        public event System.EventHandler<moveEntityFromShopCompletedEventArgs> moveEntityFromShopCompleted;
        
        public event System.EventHandler<AddShopCompletedEventArgs> AddShopCompleted;
        
        public event System.EventHandler<DeleteShopCompletedEventArgs> DeleteShopCompleted;
        
        public event System.EventHandler<GetEntityByPositionCompletedEventArgs> GetEntityByPositionCompleted;
        
        public event System.EventHandler<GetProductsByProductTypeCompletedEventArgs> GetProductsByProductTypeCompleted;
        
        public event System.EventHandler<GetStartPositionCompletedEventArgs> GetStartPositionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginGetShops(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetShops(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> Chronocourses.Client.ShopService.IShopService.EndGetShops(System.IAsyncResult result) {
            return base.Channel.EndGetShops(result);
        }
        
        private System.IAsyncResult OnBeginGetShops(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginGetShops(callback, asyncState);
        }
        
        private object[] OnEndGetShops(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndGetShops(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetShopsCompleted(object state) {
            if ((this.GetShopsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetShopsCompleted(this, new GetShopsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetShopsAsync() {
            this.GetShopsAsync(null);
        }
        
        public void GetShopsAsync(object userState) {
            if ((this.onBeginGetShopsDelegate == null)) {
                this.onBeginGetShopsDelegate = new BeginOperationDelegate(this.OnBeginGetShops);
            }
            if ((this.onEndGetShopsDelegate == null)) {
                this.onEndGetShopsDelegate = new EndOperationDelegate(this.OnEndGetShops);
            }
            if ((this.onGetShopsCompletedDelegate == null)) {
                this.onGetShopsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetShopsCompleted);
            }
            base.InvokeAsync(this.onBeginGetShopsDelegate, null, this.onEndGetShopsDelegate, this.onGetShopsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginGetShop(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetShop(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chronocourses.Client.ShopService.Shop Chronocourses.Client.ShopService.IShopService.EndGetShop(System.IAsyncResult result) {
            return base.Channel.EndGetShop(result);
        }
        
        private System.IAsyncResult OnBeginGetShop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginGetShop(id, callback, asyncState);
        }
        
        private object[] OnEndGetShop(System.IAsyncResult result) {
            Chronocourses.Client.ShopService.Shop retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndGetShop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetShopCompleted(object state) {
            if ((this.GetShopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetShopCompleted(this, new GetShopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetShopAsync(int id) {
            this.GetShopAsync(id, null);
        }
        
        public void GetShopAsync(int id, object userState) {
            if ((this.onBeginGetShopDelegate == null)) {
                this.onBeginGetShopDelegate = new BeginOperationDelegate(this.OnBeginGetShop);
            }
            if ((this.onEndGetShopDelegate == null)) {
                this.onEndGetShopDelegate = new EndOperationDelegate(this.OnEndGetShop);
            }
            if ((this.onGetShopCompletedDelegate == null)) {
                this.onGetShopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetShopCompleted);
            }
            base.InvokeAsync(this.onBeginGetShopDelegate, new object[] {
                        id}, this.onEndGetShopDelegate, this.onGetShopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginSaveShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveShop(shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Chronocourses.Client.ShopService.IShopService.EndSaveShop(System.IAsyncResult result) {
            return base.Channel.EndSaveShop(result);
        }
        
        private System.IAsyncResult OnBeginSaveShop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Chronocourses.Client.ShopService.Shop shop = ((Chronocourses.Client.ShopService.Shop)(inValues[0]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginSaveShop(shop, callback, asyncState);
        }
        
        private object[] OnEndSaveShop(System.IAsyncResult result) {
            int retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndSaveShop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveShopCompleted(object state) {
            if ((this.SaveShopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveShopCompleted(this, new SaveShopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveShopAsync(Chronocourses.Client.ShopService.Shop shop) {
            this.SaveShopAsync(shop, null);
        }
        
        public void SaveShopAsync(Chronocourses.Client.ShopService.Shop shop, object userState) {
            if ((this.onBeginSaveShopDelegate == null)) {
                this.onBeginSaveShopDelegate = new BeginOperationDelegate(this.OnBeginSaveShop);
            }
            if ((this.onEndSaveShopDelegate == null)) {
                this.onEndSaveShopDelegate = new EndOperationDelegate(this.OnEndSaveShop);
            }
            if ((this.onSaveShopCompletedDelegate == null)) {
                this.onSaveShopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveShopCompleted);
            }
            base.InvokeAsync(this.onBeginSaveShopDelegate, new object[] {
                        shop}, this.onEndSaveShopDelegate, this.onSaveShopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginmoveEntityFromShop(Chronocourses.Client.ShopService.Entity ent, System.Collections.ObjectModel.ObservableCollection<int> newPos, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginmoveEntityFromShop(ent, newPos, shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Chronocourses.Client.ShopService.IShopService.EndmoveEntityFromShop(System.IAsyncResult result) {
            return base.Channel.EndmoveEntityFromShop(result);
        }
        
        private System.IAsyncResult OnBeginmoveEntityFromShop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Chronocourses.Client.ShopService.Entity ent = ((Chronocourses.Client.ShopService.Entity)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<int> newPos = ((System.Collections.ObjectModel.ObservableCollection<int>)(inValues[1]));
            Chronocourses.Client.ShopService.Shop shop = ((Chronocourses.Client.ShopService.Shop)(inValues[2]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginmoveEntityFromShop(ent, newPos, shop, callback, asyncState);
        }
        
        private object[] OnEndmoveEntityFromShop(System.IAsyncResult result) {
            int retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndmoveEntityFromShop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnmoveEntityFromShopCompleted(object state) {
            if ((this.moveEntityFromShopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.moveEntityFromShopCompleted(this, new moveEntityFromShopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void moveEntityFromShopAsync(Chronocourses.Client.ShopService.Entity ent, System.Collections.ObjectModel.ObservableCollection<int> newPos, Chronocourses.Client.ShopService.Shop shop) {
            this.moveEntityFromShopAsync(ent, newPos, shop, null);
        }
        
        public void moveEntityFromShopAsync(Chronocourses.Client.ShopService.Entity ent, System.Collections.ObjectModel.ObservableCollection<int> newPos, Chronocourses.Client.ShopService.Shop shop, object userState) {
            if ((this.onBeginmoveEntityFromShopDelegate == null)) {
                this.onBeginmoveEntityFromShopDelegate = new BeginOperationDelegate(this.OnBeginmoveEntityFromShop);
            }
            if ((this.onEndmoveEntityFromShopDelegate == null)) {
                this.onEndmoveEntityFromShopDelegate = new EndOperationDelegate(this.OnEndmoveEntityFromShop);
            }
            if ((this.onmoveEntityFromShopCompletedDelegate == null)) {
                this.onmoveEntityFromShopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnmoveEntityFromShopCompleted);
            }
            base.InvokeAsync(this.onBeginmoveEntityFromShopDelegate, new object[] {
                        ent,
                        newPos,
                        shop}, this.onEndmoveEntityFromShopDelegate, this.onmoveEntityFromShopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginAddShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddShop(shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Chronocourses.Client.ShopService.IShopService.EndAddShop(System.IAsyncResult result) {
            return base.Channel.EndAddShop(result);
        }
        
        private System.IAsyncResult OnBeginAddShop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Chronocourses.Client.ShopService.Shop shop = ((Chronocourses.Client.ShopService.Shop)(inValues[0]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginAddShop(shop, callback, asyncState);
        }
        
        private object[] OnEndAddShop(System.IAsyncResult result) {
            int retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndAddShop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddShopCompleted(object state) {
            if ((this.AddShopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddShopCompleted(this, new AddShopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddShopAsync(Chronocourses.Client.ShopService.Shop shop) {
            this.AddShopAsync(shop, null);
        }
        
        public void AddShopAsync(Chronocourses.Client.ShopService.Shop shop, object userState) {
            if ((this.onBeginAddShopDelegate == null)) {
                this.onBeginAddShopDelegate = new BeginOperationDelegate(this.OnBeginAddShop);
            }
            if ((this.onEndAddShopDelegate == null)) {
                this.onEndAddShopDelegate = new EndOperationDelegate(this.OnEndAddShop);
            }
            if ((this.onAddShopCompletedDelegate == null)) {
                this.onAddShopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddShopCompleted);
            }
            base.InvokeAsync(this.onBeginAddShopDelegate, new object[] {
                        shop}, this.onEndAddShopDelegate, this.onAddShopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginDeleteShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteShop(shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Chronocourses.Client.ShopService.IShopService.EndDeleteShop(System.IAsyncResult result) {
            return base.Channel.EndDeleteShop(result);
        }
        
        private System.IAsyncResult OnBeginDeleteShop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Chronocourses.Client.ShopService.Shop shop = ((Chronocourses.Client.ShopService.Shop)(inValues[0]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginDeleteShop(shop, callback, asyncState);
        }
        
        private object[] OnEndDeleteShop(System.IAsyncResult result) {
            int retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndDeleteShop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteShopCompleted(object state) {
            if ((this.DeleteShopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteShopCompleted(this, new DeleteShopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteShopAsync(Chronocourses.Client.ShopService.Shop shop) {
            this.DeleteShopAsync(shop, null);
        }
        
        public void DeleteShopAsync(Chronocourses.Client.ShopService.Shop shop, object userState) {
            if ((this.onBeginDeleteShopDelegate == null)) {
                this.onBeginDeleteShopDelegate = new BeginOperationDelegate(this.OnBeginDeleteShop);
            }
            if ((this.onEndDeleteShopDelegate == null)) {
                this.onEndDeleteShopDelegate = new EndOperationDelegate(this.OnEndDeleteShop);
            }
            if ((this.onDeleteShopCompletedDelegate == null)) {
                this.onDeleteShopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteShopCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteShopDelegate, new object[] {
                        shop}, this.onEndDeleteShopDelegate, this.onDeleteShopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginGetEntityByPosition(int x, int y, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEntityByPosition(x, y, shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chronocourses.Client.ShopService.Entity Chronocourses.Client.ShopService.IShopService.EndGetEntityByPosition(System.IAsyncResult result) {
            return base.Channel.EndGetEntityByPosition(result);
        }
        
        private System.IAsyncResult OnBeginGetEntityByPosition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            Chronocourses.Client.ShopService.Shop shop = ((Chronocourses.Client.ShopService.Shop)(inValues[2]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginGetEntityByPosition(x, y, shop, callback, asyncState);
        }
        
        private object[] OnEndGetEntityByPosition(System.IAsyncResult result) {
            Chronocourses.Client.ShopService.Entity retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndGetEntityByPosition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEntityByPositionCompleted(object state) {
            if ((this.GetEntityByPositionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEntityByPositionCompleted(this, new GetEntityByPositionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEntityByPositionAsync(int x, int y, Chronocourses.Client.ShopService.Shop shop) {
            this.GetEntityByPositionAsync(x, y, shop, null);
        }
        
        public void GetEntityByPositionAsync(int x, int y, Chronocourses.Client.ShopService.Shop shop, object userState) {
            if ((this.onBeginGetEntityByPositionDelegate == null)) {
                this.onBeginGetEntityByPositionDelegate = new BeginOperationDelegate(this.OnBeginGetEntityByPosition);
            }
            if ((this.onEndGetEntityByPositionDelegate == null)) {
                this.onEndGetEntityByPositionDelegate = new EndOperationDelegate(this.OnEndGetEntityByPosition);
            }
            if ((this.onGetEntityByPositionCompletedDelegate == null)) {
                this.onGetEntityByPositionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEntityByPositionCompleted);
            }
            base.InvokeAsync(this.onBeginGetEntityByPositionDelegate, new object[] {
                        x,
                        y,
                        shop}, this.onEndGetEntityByPositionDelegate, this.onGetEntityByPositionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginGetProductsByProductType(int productTypeId, int shopId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductsByProductType(productTypeId, shopId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> Chronocourses.Client.ShopService.IShopService.EndGetProductsByProductType(System.IAsyncResult result) {
            return base.Channel.EndGetProductsByProductType(result);
        }
        
        private System.IAsyncResult OnBeginGetProductsByProductType(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int productTypeId = ((int)(inValues[0]));
            int shopId = ((int)(inValues[1]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginGetProductsByProductType(productTypeId, shopId, callback, asyncState);
        }
        
        private object[] OnEndGetProductsByProductType(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndGetProductsByProductType(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductsByProductTypeCompleted(object state) {
            if ((this.GetProductsByProductTypeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductsByProductTypeCompleted(this, new GetProductsByProductTypeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductsByProductTypeAsync(int productTypeId, int shopId) {
            this.GetProductsByProductTypeAsync(productTypeId, shopId, null);
        }
        
        public void GetProductsByProductTypeAsync(int productTypeId, int shopId, object userState) {
            if ((this.onBeginGetProductsByProductTypeDelegate == null)) {
                this.onBeginGetProductsByProductTypeDelegate = new BeginOperationDelegate(this.OnBeginGetProductsByProductType);
            }
            if ((this.onEndGetProductsByProductTypeDelegate == null)) {
                this.onEndGetProductsByProductTypeDelegate = new EndOperationDelegate(this.OnEndGetProductsByProductType);
            }
            if ((this.onGetProductsByProductTypeCompletedDelegate == null)) {
                this.onGetProductsByProductTypeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsByProductTypeCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductsByProductTypeDelegate, new object[] {
                        productTypeId,
                        shopId}, this.onEndGetProductsByProductTypeDelegate, this.onGetProductsByProductTypeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Chronocourses.Client.ShopService.IShopService.BeginGetStartPosition(int ShopID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStartPosition(ShopID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chronocourses.Client.ShopService.Entity Chronocourses.Client.ShopService.IShopService.EndGetStartPosition(System.IAsyncResult result) {
            return base.Channel.EndGetStartPosition(result);
        }
        
        private System.IAsyncResult OnBeginGetStartPosition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ShopID = ((int)(inValues[0]));
            return ((Chronocourses.Client.ShopService.IShopService)(this)).BeginGetStartPosition(ShopID, callback, asyncState);
        }
        
        private object[] OnEndGetStartPosition(System.IAsyncResult result) {
            Chronocourses.Client.ShopService.Entity retVal = ((Chronocourses.Client.ShopService.IShopService)(this)).EndGetStartPosition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStartPositionCompleted(object state) {
            if ((this.GetStartPositionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStartPositionCompleted(this, new GetStartPositionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStartPositionAsync(int ShopID) {
            this.GetStartPositionAsync(ShopID, null);
        }
        
        public void GetStartPositionAsync(int ShopID, object userState) {
            if ((this.onBeginGetStartPositionDelegate == null)) {
                this.onBeginGetStartPositionDelegate = new BeginOperationDelegate(this.OnBeginGetStartPosition);
            }
            if ((this.onEndGetStartPositionDelegate == null)) {
                this.onEndGetStartPositionDelegate = new EndOperationDelegate(this.OnEndGetStartPosition);
            }
            if ((this.onGetStartPositionCompletedDelegate == null)) {
                this.onGetStartPositionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStartPositionCompleted);
            }
            base.InvokeAsync(this.onBeginGetStartPositionDelegate, new object[] {
                        ShopID}, this.onEndGetStartPositionDelegate, this.onGetStartPositionCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Chronocourses.Client.ShopService.IShopService CreateChannel() {
            return new ShopServiceClientChannel(this);
        }
        
        private class ShopServiceClientChannel : ChannelBase<Chronocourses.Client.ShopService.IShopService>, Chronocourses.Client.ShopService.IShopService {
            
            public ShopServiceClientChannel(System.ServiceModel.ClientBase<Chronocourses.Client.ShopService.IShopService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetShops", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> EndGetShops(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop> _result = ((System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Shop>)(base.EndInvoke("GetShops", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetShop(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetShop", _args, callback, asyncState);
                return _result;
            }
            
            public Chronocourses.Client.ShopService.Shop EndGetShop(System.IAsyncResult result) {
                object[] _args = new object[0];
                Chronocourses.Client.ShopService.Shop _result = ((Chronocourses.Client.ShopService.Shop)(base.EndInvoke("GetShop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = shop;
                System.IAsyncResult _result = base.BeginInvoke("SaveShop", _args, callback, asyncState);
                return _result;
            }
            
            public int EndSaveShop(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("SaveShop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginmoveEntityFromShop(Chronocourses.Client.ShopService.Entity ent, System.Collections.ObjectModel.ObservableCollection<int> newPos, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = ent;
                _args[1] = newPos;
                _args[2] = shop;
                System.IAsyncResult _result = base.BeginInvoke("moveEntityFromShop", _args, callback, asyncState);
                return _result;
            }
            
            public int EndmoveEntityFromShop(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("moveEntityFromShop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = shop;
                System.IAsyncResult _result = base.BeginInvoke("AddShop", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddShop(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddShop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteShop(Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = shop;
                System.IAsyncResult _result = base.BeginInvoke("DeleteShop", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDeleteShop(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DeleteShop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEntityByPosition(int x, int y, Chronocourses.Client.ShopService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = x;
                _args[1] = y;
                _args[2] = shop;
                System.IAsyncResult _result = base.BeginInvoke("GetEntityByPosition", _args, callback, asyncState);
                return _result;
            }
            
            public Chronocourses.Client.ShopService.Entity EndGetEntityByPosition(System.IAsyncResult result) {
                object[] _args = new object[0];
                Chronocourses.Client.ShopService.Entity _result = ((Chronocourses.Client.ShopService.Entity)(base.EndInvoke("GetEntityByPosition", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductsByProductType(int productTypeId, int shopId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = productTypeId;
                _args[1] = shopId;
                System.IAsyncResult _result = base.BeginInvoke("GetProductsByProductType", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> EndGetProductsByProductType(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product> _result = ((System.Collections.ObjectModel.ObservableCollection<Chronocourses.Client.ShopService.Product>)(base.EndInvoke("GetProductsByProductType", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStartPosition(int ShopID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ShopID;
                System.IAsyncResult _result = base.BeginInvoke("GetStartPosition", _args, callback, asyncState);
                return _result;
            }
            
            public Chronocourses.Client.ShopService.Entity EndGetStartPosition(System.IAsyncResult result) {
                object[] _args = new object[0];
                Chronocourses.Client.ShopService.Entity _result = ((Chronocourses.Client.ShopService.Entity)(base.EndInvoke("GetStartPosition", _args, result)));
                return _result;
            }
        }
    }
}
