//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18046
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronocourses.Manager.TypeProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, Chronocourses.Manager.TypeProductService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, Chronocourses.Manager.TypeProductService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/Chronocourses.Model", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TypeProductService.ITypeProductService")]
    public interface ITypeProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeProductService/GetTypeProducts", ReplyAction="http://tempuri.org/ITypeProductService/GetTypeProductsResponse")]
        Chronocourses.Model.TypeProduct[] GetTypeProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeProductService/GetTypeProduct", ReplyAction="http://tempuri.org/ITypeProductService/GetTypeProductResponse")]
        Chronocourses.Model.TypeProduct GetTypeProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeProductService/SaveTypeProduct", ReplyAction="http://tempuri.org/ITypeProductService/SaveTypeProductResponse")]
        void SaveTypeProduct(Chronocourses.Model.TypeProduct typeProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeProductService/AddTypeProduct", ReplyAction="http://tempuri.org/ITypeProductService/AddTypeProductResponse")]
        void AddTypeProduct(Chronocourses.Model.TypeProduct typeProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeProductService/DeleteTypeProduct", ReplyAction="http://tempuri.org/ITypeProductService/DeleteTypeProductResponse")]
        void DeleteTypeProduct(Chronocourses.Model.TypeProduct typeProduct);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITypeProductServiceChannel : Chronocourses.Manager.TypeProductService.ITypeProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TypeProductServiceClient : System.ServiceModel.ClientBase<Chronocourses.Manager.TypeProductService.ITypeProductService>, Chronocourses.Manager.TypeProductService.ITypeProductService {
        
        public TypeProductServiceClient() {
        }
        
        public TypeProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TypeProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Chronocourses.Model.TypeProduct[] GetTypeProducts() {
            return base.Channel.GetTypeProducts();
        }
        
        public Chronocourses.Model.TypeProduct GetTypeProduct(int id) {
            return base.Channel.GetTypeProduct(id);
        }
        
        public void SaveTypeProduct(Chronocourses.Model.TypeProduct typeProduct) {
            base.Channel.SaveTypeProduct(typeProduct);
        }
        
        public void AddTypeProduct(Chronocourses.Model.TypeProduct typeProduct) {
            base.Channel.AddTypeProduct(typeProduct);
        }
        
        public void DeleteTypeProduct(Chronocourses.Model.TypeProduct typeProduct) {
            base.Channel.DeleteTypeProduct(typeProduct);
        }
    }
}
